language: node_js
node_js:
  - "stable"

scripts:
  - npm install
  - npm run test
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  domain: 
  project: ./build

on:
  branch: master